# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Style/StringLiterals:
  Exclude:
    - "config/**/*"

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false
